apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: ${NAMESPACE}
spec:
  instances: ${INSTANCE_COUNT}
  #superuserSecret:
  #  name: superuser-secret
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
  bootstrap:
    initdb:
      database: ${APP_DB}
      owner: ${APP_USER} 
  #    secret:
  #      name: app-secret
  storage:
    size: '10Gi'
  enableSuperuserAccess: true
  backup:
    barmanObjectStore:
      destinationPath: "s3://test-beauburra/cloudnative-pg"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY

---
apiVersion: v1
kind: Pod
metadata:
  name: pgclient
  namespace: ${NAMESPACE}
spec:
  containers:
  - name: pgclient
    image: postgres
    command: ["sleep"]
    args: ["3600"]  # Keeps the container running for an hour
