apiVersion: v1
kind: Pod
metadata:
  name: web-pvc-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sleep", "infinity"]
    volumeMounts:
    - mountPath: "/mnt/data"
      name: web-volume
  volumes:
  - name: web-volume
    persistentVolumeClaim:
      claimName: web-pvc
